const STORAGE={url:"spirit:n8n-url",secret:"spirit:queue-secret"};
const state={queue:[],selected:null,status:"pending",kind:"all",history:[],events:[],tasks:[],notes:[],homework:[],month:new Date()};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles={queue:"Очередь изменений",calendar:"Календарь",tasks:"Сводка задач",notes:"Конспекты",homework:"Практическое ДЗ",chat:"Чат с ассистентом",sources:"Источники данных"};
function settings(){return{url:(localStorage.getItem(STORAGE.url)||"").replace(/\/+$/,""),secret:localStorage.getItem(STORAGE.secret)||""}}
function parse(raw){try{return typeof raw==="object"?raw:JSON.parse(raw)}catch{return{}}}
async function api(path,payload={}){const c=settings();if(!c.url||!c.secret)throw new Error("Сначала настрой подключение к n8n");const r=await fetch(`${c.url}/webhook/${path}`,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:JSON.stringify({...payload,secret:c.secret})});const data=parse(await r.text());if(!r.ok||data.error)throw new Error(data.error||`n8n: ${r.status}`);return data}
async function readData(path){const r=await fetch(`${path}?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`Не удалось прочитать ${path}`);return r.json()}
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function date(v,time=true){if(!v)return"без даты";const d=new Date(v);return isNaN(d)?String(v):new Intl.DateTimeFormat("ru-RU",time?{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}:{day:"numeric",month:"long",year:"numeric"}).format(d)}
const kindLabel=(k,s)=>k==="homework"?(s==="theory"?"Теоретическое ДЗ":"Практическое ДЗ"):({event:"Событие",task:"Задача",news:"Новость"})[k]||"Предложение";
const sourceLabel=s=>({gmail:"Gmail",telegram:"Telegram",mesh:"МЭШ",chat:"Чат"})[s?.type]||s?.title||"Источник";
const statusLabel=s=>({pending:"Ожидает",approved:"Принято",rejected:"Отклонено"})[s]||s;
const actionLabel=a=>({calendar:"Добавить событие в календарь",task_summary:"Добавить задачу в сводку",note:"Создать конспект через ChatGPTAutomation",homework_solver:"Решить ДЗ через ChatGPTAutomation",news_digest:"Добавить новость"})[a]||a;
function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),3500)}
function connection(mode,text){$("#connectionDot").className=mode;$("#connectionText").textContent=text}
function renderQueue(){const counts={pending:0,approved:0,rejected:0};state.queue.forEach(i=>counts[i.status]=(counts[i.status]||0)+1);for(const s of Object.keys(counts))$(`#${s}Count`).textContent=counts[s];$("#navPending").textContent=counts.pending;const items=state.queue.filter(i=>(state.status==="all"||i.status===state.status)&&(state.kind==="all"||i.kind===state.kind));$("#queueList").innerHTML=items.length?items.map(i=>`<button class="queue-card ${state.selected===i.id?"selected":""}" data-id="${esc(i.id)}"><div class="card-top"><span class="type-icon">•</span><h3>${esc(i.title)}</h3><span class="status ${i.status}">${statusLabel(i.status)}</span></div><p>${esc(i.summary||i.reason||"")}</p><div class="meta-row"><span>${kindLabel(i.kind,i.subtype)}</span><span>·</span><span>${sourceLabel(i.source)}</span><span>·</span><span>${date(i.created_at)}</span></div></button>`).join(""):'<div class="empty-list">Очередь пуста.</div>';$$(".queue-card").forEach(b=>b.onclick=()=>{state.selected=b.dataset.id;renderQueue()});renderDetails()}
function renderDetails(){const i=state.queue.find(x=>x.id===state.selected),p=$("#detailsPanel");if(!i){p.innerHTML='<div class="empty-details"><span>⌁</span><h2>Выбери предложение</h2><p>Здесь появятся источник, причина и данные.</p></div>';return}p.innerHTML=`<div class="detail-content"><header><span class="status ${i.status}">${statusLabel(i.status)}</span><h2>${esc(i.title)}</h2><p>${esc(i.summary||"")}</p></header><div class="detail-body"><div class="detail-block"><h3>Что произойдёт</h3><p>${esc(actionLabel(i.action))}</p></div><div class="detail-block"><h3>Почему</h3><p>${esc(i.reason||"")}</p></div><div class="detail-block"><h3>Источник</h3><p>${esc(sourceLabel(i.source))}</p></div><div class="detail-block"><h3>Данные</h3><pre class="payload">${esc(JSON.stringify(i.payload||{},null,2))}</pre></div></div>${i.status==="pending"?'<div class="detail-actions"><button class="primary-button" data-decision="approve">Подтвердить</button><button class="danger-button" data-decision="reject">Отклонить</button></div>':""}</div>`;$$("[data-decision]").forEach(b=>b.onclick=()=>decide(i.id,b.dataset.decision))}
async function loadQueue(){const c=settings();$("#setupNotice").classList.toggle("hidden",!!(c.url&&c.secret));if(!c.url||!c.secret){state.queue=[];connection("","n8n не настроен");renderQueue();return}try{const data=await api("sj-queue");state.queue=data.queue||[];connection("online","n8n подключён");renderQueue()}catch(e){state.queue=[];renderQueue();connection("error","Ошибка подключения");toast(e.message)}}
async function decide(id,decision){if(!confirm(decision==="approve"?"Подтвердить изменение?":"Отклонить предложение?"))return;try{await api("sj-queue-decision",{id,decision});await Promise.all([loadQueue(),loadRepositoryData()]);toast("Готово")}catch(e){toast(e.message)}}
async function loadRepositoryData(){try{const [c,t,n,h]=await Promise.all([readData("data/calendar.json"),readData("data/tasks.json"),readData("data/notes/index.json"),readData("data/homework/index.json")]);state.events=c.events||[];state.tasks=t.tasks||[];state.notes=n.notes||[];state.homework=h.items||[];$("#tasksUpdated").textContent=t.updated_at?`Обновлено ${date(t.updated_at)}`:"Пока нет изменений";renderCalendar();renderTasks();renderLibrary("notes");renderLibrary("homework")}catch(e){toast(e.message)}}
function dayKey(d){return isNaN(d)?"":`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7));$("#calendarMonth").textContent=new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(first);let html=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x=>`<div class="calendar-cell calendar-weekday">${x}</div>`).join("");for(let o=0;o<42;o++){const d=new Date(start);d.setDate(start.getDate()+o);const events=state.events.filter(e=>dayKey(new Date(e.start_at||e.date))===dayKey(d));html+=`<div class="calendar-cell ${d.getMonth()===m?"":"outside"} ${dayKey(d)===dayKey(new Date())?"today":""}"><span class="calendar-day">${d.getDate()}</span>${events.slice(0,3).map(e=>`<span class="calendar-event">${esc(e.title)}</span>`).join("")}</div>`}$("#calendarGrid").innerHTML=html;const upcoming=state.events.filter(e=>new Date(e.start_at||e.date)>=new Date(Date.now()-86400000)).sort((a,b)=>new Date(a.start_at||a.date)-new Date(b.start_at||b.date)).slice(0,8);$("#calendarTimeline").innerHTML=upcoming.length?upcoming.map(e=>`<article class="timeline-item"><time>${date(e.start_at||e.date)}</time><i class="timeline-dot"></i><div><h3>${esc(e.title)}</h3><p>${esc(e.description||e.location||"")}</p></div></article>`).join(""):'<div class="empty-list">Предстоящих событий пока нет.</div>'}
function renderTasks(){const defs=[["q1","Сделать сейчас","Важно и срочно"],["q2","Запланировать","Важно, не срочно"],["q3","Быстро закрыть","Срочно, не важно"],["q4","Когда будет время","Не срочно и не важно"]];$("#taskBoard").innerHTML=defs.map(([q,title,sub])=>{const tasks=state.tasks.filter(t=>(t.quadrant||"q2")===q);return `<section class="task-quadrant ${q}"><div class="quadrant-heading"><i></i><div><h3>${title}</h3><span>${sub}</span></div><span>${tasks.length}</span></div><div class="task-cards">${tasks.length?tasks.map(t=>`<article class="task-card ${t.status==="done"?"done":""}"><strong>${esc(t.title)}</strong><p>${esc(t.description||"")}</p><footer><span>${esc(t.subject||"Без предмета")}</span><span>·</span><span>${t.due_at?date(t.due_at,false):"без срока"}</span></footer></article>`).join(""):'<div class="empty-list">Пусто</div>'}</div></section>`}).join("")}
function renderLibrary(type){const items=type==="notes"?state.notes:state.homework,target=type==="notes"?$("#notesGrid"):$("#homeworkGrid");target.innerHTML=items.length?items.map((i,n)=>`<button class="library-card" data-library="${type}" data-index="${n}"><span class="subject">${esc(i.subject||"Без предмета")}</span><h3>${esc(i.title)}</h3><p>${esc(i.summary||i.task||"")}</p><footer><span>${date(i.created_at,false)}</span><span>Открыть →</span></footer></button>`).join(""):`<div class="empty-library"><strong>${type==="notes"?"Конспектов":"Решений"} пока нет</strong><p>Создай запрос кнопкой сверху.</p></div>`;target.querySelectorAll("[data-library]").forEach(b=>b.onclick=()=>openMaterial(type,Number(b.dataset.index)))}
async function openMaterial(type,index){const i=(type==="notes"?state.notes:state.homework)[index];if(!i)return;$("#readerKind").textContent=type==="notes"?"КОНСПЕКТ":"РЕШЕНИЕ ДЗ";$("#readerTitle").textContent=i.title;try{const md=i.path?await fetch(i.path).then(r=>{if(!r.ok)throw Error("Файл не найден");return r.text()}):i.content||i.answer||"";$("#readerBody").innerHTML=markdown(md);$("#readerDialog").showModal()}catch(e){toast(e.message)}}
function markdown(md){let x=esc(md);return "<p>"+x.replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/`([^`]+)`/g,"<code>$1</code>").replace(/^&gt; (.+)$/gm,"<blockquote>$1</blockquote>").replace(/^- (.+)$/gm,"<li>$1</li>").replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>').replace(/\n{2,}/g,"</p><p>").replace(/\n/g,"<br>")+"</p>"}
function openSettings(){const c=settings();$("#n8nUrl").value=c.url;$("#queueSecret").value=c.secret;$("#settingsDialog").showModal()}
function switchView(name){$$(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));$$(".view").forEach(v=>v.classList.toggle("active",v.id===name+"View"));$("#pageTitle").textContent=titles[name];$("#refreshButton").classList.toggle("hidden",name!=="queue");$(".sidebar").classList.remove("open");location.hash=name}
function requestMaterial(mode){$("#contentMode").value=mode;$("#contentTitle").textContent=mode==="note"?"Заказать конспект":"Решить практическое ДЗ";$("#contentEyebrow").textContent=mode==="note"?"ТЕОРИЯ":"ПРАКТИКА";$("#contentDialog").showModal()}
function addMessage(role,text,extra=""){state.history.push({role,content:text});const n=document.createElement("div");n.className=`message ${role} ${extra}`;n.textContent=text;$("#messages").append(n)}
$$(".nav-item[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("#menuButton").onclick=()=>$(".sidebar").classList.toggle("open");$("#openSettings").onclick=openSettings;$("#noticeSettings").onclick=openSettings;$("#refreshButton").onclick=()=>Promise.all([loadQueue(),loadRepositoryData()]);
$("#calendarPrev").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$("#calendarNext").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};
$("#statusFilters").onclick=e=>{const b=e.target.closest("button");if(!b)return;$$("#statusFilters button").forEach(x=>x.classList.toggle("active",x===b));state.status=b.dataset.status;renderQueue()};$("#kindFilter").onchange=e=>{state.kind=e.target.value;renderQueue()};
$("#settingsForm").onsubmit=e=>{if(e.submitter?.value!=="save")return;e.preventDefault();localStorage.setItem(STORAGE.url,$("#n8nUrl").value.trim().replace(/\/+$/,""));localStorage.setItem(STORAGE.secret,$("#queueSecret").value.trim());$("#settingsDialog").close();loadQueue();toast("Настройки сохранены")};$("#testConnection").onclick=async()=>{localStorage.setItem(STORAGE.url,$("#n8nUrl").value.trim().replace(/\/+$/,""));localStorage.setItem(STORAGE.secret,$("#queueSecret").value.trim());try{await api("sj-queue");toast("Соединение работает")}catch(e){toast(e.message)}};$("#clearSettings").onclick=()=>{localStorage.removeItem(STORAGE.url);localStorage.removeItem(STORAGE.secret);toast("Настройки очищены")};
$("#chatForm").onsubmit=async e=>{e.preventDefault();const input=$("#chatInput"),text=input.value.trim();if(!text)return;addMessage("user",text);input.value="";e.submitter.disabled=true;try{const data=await api("sj-chat",{text,history:state.history.slice(-12)});addMessage("assistant",data.reply||"Ответ получен");if(data.queued?.length){toast("Предложение добавлено в очередь");loadQueue()}}catch(err){addMessage("assistant",err.message,"error")}finally{e.submitter.disabled=false}};
$("#telegramImportForm").onsubmit=async e=>{e.preventDefault();const text=$("#telegramText").value.trim();if(!text)return;e.submitter.disabled=true;try{const data=await api("sj-chat",{text,history:[],source_type:"telegram",source_title:$("#telegramChat").value.trim()||"Telegram",source_sender:$("#telegramSender").value.trim()||"не указан"});$("#telegramImportForm").reset();toast(data.queued?.length?"Сообщение разобрано и добавлено в очередь":"Сообщение разобрано, изменений не найдено");await loadQueue();switchView("queue")}catch(err){toast(err.message)}finally{e.submitter.disabled=false}};
$$(".content-request").forEach(b=>b.onclick=()=>requestMaterial(b.dataset.mode));$("#contentForm").onsubmit=async e=>{if(e.submitter?.value!=="submit")return;e.preventDefault();const mode=$("#contentMode").value,subject=$("#contentSubject").value.trim(),task=$("#contentPrompt").value.trim(),sources=$("#contentSources").value.trim();const text=mode==="note"?`Добавь в очередь теоретический конспект. Предмет: ${subject}. Тема и требования: ${task}. Источники: ${sources||"нет"}. action строго note.`:`Добавь в очередь решение практического ДЗ. Предмет: ${subject}. Условие: ${task}. Источники: ${sources||"нет"}. action строго homework_solver.`;try{const data=await api("sj-chat",{text,history:[]});$("#contentDialog").close();$("#contentForm").reset();toast(data.queued?.length?"Запрос добавлен в очередь":"Предложение не создано");await loadQueue();switchView("queue")}catch(err){toast(err.message)}};
const initial=location.hash.slice(1);if(titles[initial])switchView(initial);loadQueue();loadRepositoryData();
