const STORAGE={url:"spirit:n8n-url",secret:"spirit:queue-secret"};
const FOLDERS=[{key:"textbooks",name:"Учебники",icon:"▤"},{key:"handouts",name:"Распечатки",icon:"▧"},{key:"completed_homework",name:"Готовые ДЗ",icon:"✓"},{key:"notes",name:"Конспекты",icon:"≡"},{key:"mail",name:"Файлы из почты",icon:"✉"},{key:"telegram",name:"Файлы из Telegram",icon:"➤"}];
const GITHUB={owner:"Jeronion",repo:"SpiritJeronion",branch:"main"};
const SCHOOL_FOLDERS={textbooks:"Textbooks",handouts:"Handouts",completed_homework:"CompletedHomework",notes:"Notes",mail:"MailAttachments",telegram:"TelegramAttachments"};
const state={queue:[],selected:null,status:"pending",kind:"all",events:[],tasks:[],month:new Date(),folder:"textbooks",files:[],selectedFile:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles={queue:"Очередь изменений",calendar:"Календарь",tasks:"Сводка задач",files:"Учебные файлы"};
function settings(){return{url:(localStorage.getItem(STORAGE.url)||"").replace(/\/+$/,""),secret:localStorage.getItem(STORAGE.secret)||""}}
function applyBootstrap(){const raw=location.hash.slice(1);if(!raw.startsWith("setup="))return false;try{const encoded=raw.slice(6).replace(/-/g,"+").replace(/_/g,"/");const padded=encoded+"=".repeat((4-encoded.length%4)%4);const bytes=Uint8Array.from(atob(padded),c=>c.charCodeAt(0));const config=JSON.parse(new TextDecoder().decode(bytes));const url=String(config.url||"").replace(/\/+$/,""),secret=String(config.secret||"");if(!/^https:\/\/[a-z0-9.-]+(?::\d+)?$/i.test(url)||!secret)throw new Error("invalid_bootstrap");localStorage.setItem(STORAGE.url,url);localStorage.setItem(STORAGE.secret,secret);history.replaceState(null,"",`${location.pathname}${location.search}#queue`);return true}catch{history.replaceState(null,"",`${location.pathname}${location.search}#queue`);return false}}
function parse(raw){try{return typeof raw==="object"?raw:JSON.parse(raw)}catch{return{}}}
async function api(path,payload={}){const c=settings();if(!c.url||!c.secret)throw new Error("Сначала настрой подключение к n8n");const r=await fetch(`${c.url}/webhook/${path}`,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:JSON.stringify({...payload,secret:c.secret})});const data=parse(await r.text());if(!r.ok||data.error)throw new Error(data.error||`n8n: ${r.status}`);return data}
async function readData(path){const r=await fetch(`${path}?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`Не удалось прочитать ${path}`);return r.json()}
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function date(v,time=true){if(!v)return"без даты";const d=new Date(v);return isNaN(d)?String(v):new Intl.DateTimeFormat("ru-RU",time?{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}:{day:"numeric",month:"long",year:"numeric"}).format(d)}
const kindLabel=(k,s)=>k==="homework"?(s==="theory"?"Теоретическое ДЗ":"Практическое ДЗ"):({event:"Событие",task:"Задача",news:"Новость"})[k]||"Предложение";
const sourceLabel=s=>({gmail:"Gmail",telegram:"Telegram",mesh:"МЭШ",chat:"Чат"})[s?.type]||s?.title||"Источник";
const statusLabel=s=>({pending:"Ожидает",approved:"Принято",rejected:"Отклонено"})[s]||s;
const actionLabel=a=>({calendar:"Добавить событие в календарь",task_summary:"Добавить задачу в сводку",note:"Создать конспект через ChatGPTAutomation",homework_solver:"Решить ДЗ через ChatGPTAutomation",news_digest:"Добавить новость"})[a]||a;
function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),3500)}
function connection(mode,text){$("#connectionDot").className=mode;$("#connectionText").textContent=text}
function renderQueue(){const counts={pending:0,approved:0,rejected:0};state.queue.forEach(i=>counts[i.status]=(counts[i.status]||0)+1);for(const s of Object.keys(counts))$(`#${s}Count`).textContent=counts[s];$("#navPending").textContent=counts.pending;const items=state.queue.filter(i=>(state.status==="all"||i.status===state.status)&&(state.kind==="all"||i.kind===state.kind));$("#queueList").innerHTML=items.length?items.map(i=>`<button class="queue-card ${state.selected===i.id?"selected":""}" data-id="${esc(i.id)}"><div class="card-top"><span class="type-icon">•</span><h3>${esc(i.title)}</h3><span class="status ${i.status}">${statusLabel(i.status)}</span></div><p>${esc(i.summary||i.reason||"")}</p><div class="meta-row"><span>${kindLabel(i.kind,i.subtype)}</span><span>·</span><span>${sourceLabel(i.source)}</span><span>·</span><span>${date(i.created_at)}</span></div></button>`).join(""):'<div class="empty-list">Очередь пуста.</div>';$$(".queue-card").forEach(b=>b.onclick=()=>{state.selected=b.dataset.id;renderQueue()});renderDetails()}
function renderDetails(){const i=state.queue.find(x=>x.id===state.selected),p=$("#detailsPanel");if(!i){p.innerHTML='<div class="empty-details"><span>⌁</span><h2>Выбери предложение</h2><p>Здесь появятся источник, причина и данные.</p></div>';return}p.innerHTML=`<div class="detail-content"><header><span class="status ${i.status}">${statusLabel(i.status)}</span><h2>${esc(i.title)}</h2><p>${esc(i.summary||"")}</p></header><div class="detail-body"><div class="detail-block"><h3>Что произойдёт</h3><p>${esc(actionLabel(i.action))}</p></div><div class="detail-block"><h3>Почему</h3><p>${esc(i.reason||"")}</p></div><div class="detail-block"><h3>Источник</h3><p>${esc(sourceLabel(i.source))}</p></div><div class="detail-block"><h3>Данные</h3><pre class="payload">${esc(JSON.stringify(i.payload||{},null,2))}</pre></div></div>${i.status==="pending"?'<div class="detail-actions"><button class="primary-button" data-decision="approve">Подтвердить</button><button class="secondary-button" data-edit-queue>Исправить</button><button class="danger-button" data-decision="reject">Отклонить</button></div>':""}</div>`;$$("[data-decision]").forEach(b=>b.onclick=()=>decide(i.id,b.dataset.decision));const edit=p.querySelector("[data-edit-queue]");if(edit)edit.onclick=()=>openQueueEditor(i)}
function queueType(i){if(i.kind==="homework")return i.action==="note"?"homework-theory":"homework-assignment";return i.kind||"task"}
function openQueueEditor(i){$("#editQueueId").value=i.id;$("#editQueueType").value=queueType(i);$("#editQueueTitle").value=i.title||"";$("#editQueueSummary").value=i.summary||"";$("#editQueueReason").value=i.reason||"";$("#editQueuePayload").value=JSON.stringify(i.payload||{},null,2);$("#editQueueDialog").showModal()}
async function loadQueue(){const c=settings();$("#setupNotice").classList.toggle("hidden",!!(c.url&&c.secret));if(!c.url||!c.secret){state.queue=[];connection("","n8n не настроен");renderQueue();return}try{const data=await api("sj-queue");state.queue=data.queue||[];connection("online","n8n подключён");renderQueue()}catch(e){state.queue=[];renderQueue();connection("error","Ошибка подключения");toast(e.message)}}
async function decide(id,decision){if(!confirm(decision==="approve"?"Подтвердить изменение?":"Отклонить предложение?"))return;try{await api("sj-queue-decision",{id,decision});await Promise.all([loadQueue(),loadRepositoryData()]);toast("Готово")}catch(e){toast(e.message)}}
async function loadRepositoryData(){try{const [c,t]=await Promise.all([readData("data/calendar.json"),readData("data/tasks.json")]);state.events=c.events||[];state.tasks=t.tasks||[];$("#tasksUpdated").textContent=t.updated_at?"Обновлено "+date(t.updated_at):"Пока нет изменений";renderCalendar();renderTasks()}catch(e){toast(e.message)}}
function dayKey(d){return isNaN(d)?"":`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7));$("#calendarMonth").textContent=new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(first);let html=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x=>`<div class="calendar-cell calendar-weekday">${x}</div>`).join("");for(let o=0;o<42;o++){const d=new Date(start);d.setDate(start.getDate()+o);const events=state.events.filter(e=>dayKey(new Date(e.start_at||e.date))===dayKey(d));html+=`<div class="calendar-cell ${d.getMonth()===m?"":"outside"} ${dayKey(d)===dayKey(new Date())?"today":""}"><span class="calendar-day">${d.getDate()}</span>${events.slice(0,3).map(e=>`<span class="calendar-event">${esc(e.title)}</span>`).join("")}</div>`}$("#calendarGrid").innerHTML=html;const upcoming=state.events.filter(e=>new Date(e.start_at||e.date)>=new Date(Date.now()-86400000)).sort((a,b)=>new Date(a.start_at||a.date)-new Date(b.start_at||b.date)).slice(0,8);$("#calendarTimeline").innerHTML=upcoming.length?upcoming.map(e=>`<article class="timeline-item"><time>${date(e.start_at||e.date)}</time><i class="timeline-dot"></i><div><h3>${esc(e.title)}</h3><p>${esc(e.description||e.location||"")}</p></div></article>`).join(""):'<div class="empty-list">Предстоящих событий пока нет.</div>'}
function renderTasks(){const defs=[["q1","Сделать сейчас","Важно и срочно"],["q2","Запланировать","Важно, не срочно"],["q3","Быстро закрыть","Срочно, не важно"],["q4","Когда будет время","Не срочно и не важно"]];$("#taskBoard").innerHTML=defs.map(([q,title,sub])=>{const tasks=state.tasks.filter(t=>(t.quadrant||"q2")===q);return `<section class="task-quadrant ${q}"><div class="quadrant-heading"><i></i><div><h3>${title}</h3><span>${sub}</span></div><span>${tasks.length}</span></div><div class="task-cards">${tasks.length?tasks.map(t=>`<article class="task-card ${t.status==="done"?"done":""}"><strong>${esc(t.title)}</strong><p>${esc(t.description||"")}</p><footer><span>${esc(t.subject||"Без предмета")}</span><span>·</span><span>${t.due_at?date(t.due_at,false):"без срока"}</span></footer></article>`).join(""):'<div class="empty-list">Пусто</div>'}</div></section>`}).join("")}
function fileExt(name=""){const p=String(name).toLowerCase().split(".");return p.length>1?p.pop():"файл"}
function fileSize(v=0){if(!v)return"—";if(v<1024)return v+" Б";if(v<1048576)return(v/1024).toFixed(1)+" КБ";return(v/1048576).toFixed(1)+" МБ"}
function renderFolders(){$("#folderTree").innerHTML=FOLDERS.map(f=>'<button class="folder-button '+(state.folder===f.key?"active":"")+'" data-folder="'+f.key+'"><span>'+f.icon+'</span>'+f.name+'<b>'+(state.folder===f.key?state.files.length:"")+'</b></button>').join("");$$("[data-folder]").forEach(b=>b.onclick=()=>loadFiles(b.dataset.folder))}
function renderFiles(){renderFolders();const folder=FOLDERS.find(f=>f.key===state.folder);$("#currentFolder").textContent=folder?folder.name:"";$("#fileList").innerHTML=state.files.length?state.files.map(f=>'<button class="file-row '+(state.selectedFile===f.name?"active":"")+'" data-file="'+esc(f.name)+'"><div class="file-name"><i>'+((["md","txt","json","csv"].includes(fileExt(f.name)))?"▤":"▱")+'</i><span>'+esc(f.name)+'</span></div><span>'+fileSize(f.size)+'</span><span>'+esc(fileExt(f.name).toUpperCase())+'</span></button>').join(""):'<div class="empty-list">В этой папке пока нет файлов.</div>';$$("[data-file]").forEach(b=>b.onclick=()=>openFile(b.dataset.file))}
async function githubFiles(folder){const dir=SCHOOL_FOLDERS[folder];if(!dir)throw new Error("Неизвестная папка");const path=`SchoolFiles/${dir}`;const url=`https://api.github.com/repos/${GITHUB.owner}/${GITHUB.repo}/contents/${path}?ref=${GITHUB.branch}`;const r=await fetch(url,{cache:"no-store",headers:{Accept:"application/vnd.github+json"}});if(!r.ok)throw new Error(`GitHub: ${r.status}`);const data=await r.json();return(Array.isArray(data)?data:[data]).map(f=>({...f,download_url:f.download_url||`https://raw.githubusercontent.com/${GITHUB.owner}/${GITHUB.repo}/${GITHUB.branch}/${path}/${encodeURIComponent(f.name)}`}))}
async function githubFile(folder,name){const files=await githubFiles(folder),file=files.find(f=>f.name===name);if(!file)throw new Error("Файл не найден в GitHub");const text=["md","txt","json","csv","log"].includes(fileExt(name));let content=null;if(text){const r=await fetch(file.download_url,{cache:"no-store"});if(!r.ok)throw new Error(`GitHub: ${r.status}`);content=await r.text()}return{...file,content}}
async function loadFiles(folder=state.folder){state.folder=folder;state.files=[];state.selectedFile=null;$("#filePreview").innerHTML='<div class="empty-details"><span>▱</span><h2>Выбери файл</h2><p>Предпросмотр появится здесь.</p></div>';renderFiles();try{let data;try{data=await api("sj-files-read",{action:"list",category:folder})}catch{data=await githubFiles(folder)}state.files=(Array.isArray(data)?data:[data]).filter(f=>f&&f.name&&f.name!==".gitkeep"&&f.type!=="dir");renderFiles()}catch(e){$("#fileList").innerHTML='<div class="empty-list">'+esc(e.message)+'</div>'}}
async function openFile(name){state.selectedFile=name;renderFiles();$("#filePreview").innerHTML='<div class="empty-details"><span>…</span><h2>Загрузка</h2></div>';try{let d;try{d=await api("sj-files-read",{action:"get",category:state.folder,filename:name})}catch{d=await githubFile(state.folder,name)}const text=["md","txt","json","csv","log"].includes(fileExt(name));$("#filePreview").innerHTML='<div class="preview-content"><header><span class="eyebrow">'+esc(fileExt(name).toUpperCase())+'</span><h3>'+esc(name)+'</h3><p>'+fileSize(d.size)+'</p></header><div class="preview-body">'+(text&&d.content!=null?markdown(d.content):"<p>Для этого формата доступен просмотр через GitHub.</p>")+'</div>'+(d.html_url?'<a class="preview-link" href="'+esc(d.html_url)+'" target="_blank" rel="noopener">Открыть в GitHub →</a>':"")+'</div>'}catch(e){$("#filePreview").innerHTML='<div class="empty-details"><h2>Не удалось открыть</h2><p>'+esc(e.message)+'</p></div>'}}
function markdown(md){let x=esc(md);return "<p>"+x.replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/`([^`]+)`/g,"<code>$1</code>").replace(/^&gt; (.+)$/gm,"<blockquote>$1</blockquote>").replace(/^- (.+)$/gm,"<li>$1</li>").replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>').replace(/\n{2,}/g,"</p><p>").replace(/\n/g,"<br>")+"</p>"}
function openSettings(){const c=settings();$("#n8nUrl").value=c.url;$("#queueSecret").value=c.secret;$("#settingsDialog").showModal()}
function switchView(name){if(!titles[name])name="queue";$$(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));$$(".view").forEach(v=>v.classList.toggle("active",v.id===name+"View"));$("#pageTitle").textContent=titles[name];$(".sidebar").classList.remove("open");location.hash=name;if(name==="files")loadFiles()}
function requestMaterial(mode){$("#contentMode").value=mode;$("#contentTitle").textContent=mode==="note"?"Заказать конспект":"Решить практическое ДЗ";$("#contentEyebrow").textContent=mode==="note"?"ТЕОРИЯ":"ПРАКТИКА";$("#contentDialog").showModal()}
$$(".nav-item[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("#menuButton").onclick=()=>$(".sidebar").classList.toggle("open");$("#openSettings").onclick=openSettings;$("#noticeSettings").onclick=openSettings;$("#refreshButton").onclick=()=>Promise.all([loadQueue(),loadRepositoryData(),location.hash==="#files"?loadFiles():Promise.resolve()]);
$("#calendarPrev").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$("#calendarNext").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};$("#calendarToday").onclick=()=>{state.month=new Date();renderCalendar()};
$("#statusFilters").onclick=e=>{const b=e.target.closest("button");if(!b)return;$$("#statusFilters button").forEach(x=>x.classList.toggle("active",x===b));state.status=b.dataset.status;renderQueue()};$("#kindFilter").onchange=e=>{state.kind=e.target.value;renderQueue()};
$("#settingsForm").onsubmit=e=>{if(e.submitter?.value!=="save")return;e.preventDefault();localStorage.setItem(STORAGE.url,$("#n8nUrl").value.trim().replace(/\/+$/,""));localStorage.setItem(STORAGE.secret,$("#queueSecret").value.trim());$("#settingsDialog").close();loadQueue();toast("Настройки сохранены")};$("#testConnection").onclick=async()=>{localStorage.setItem(STORAGE.url,$("#n8nUrl").value.trim().replace(/\/+$/,""));localStorage.setItem(STORAGE.secret,$("#queueSecret").value.trim());try{await api("sj-queue");toast("Соединение работает")}catch(e){toast(e.message)}};$("#clearSettings").onclick=()=>{localStorage.removeItem(STORAGE.url);localStorage.removeItem(STORAGE.secret);toast("Настройки очищены")};
$("#editQueueForm").onsubmit=async e=>{if(e.submitter?.value!=="save")return;e.preventDefault();let payload;try{payload=JSON.parse($("#editQueuePayload").value)}catch{return toast("Данные JSON заполнены с ошибкой")};const type=$("#editQueueType").value,map={event:{kind:"event",subtype:"personal",action:"calendar"},task:{kind:"task",subtype:"personal",action:"task_summary"},"homework-theory":{kind:"homework",subtype:"theory",action:"note"},"homework-assignment":{kind:"homework",subtype:"assignment",action:"homework_solver"},news:{kind:"news",subtype:"announcement",action:"news_digest"}};const changes={...map[type],title:$("#editQueueTitle").value.trim(),summary:$("#editQueueSummary").value.trim(),reason:$("#editQueueReason").value.trim(),payload};e.submitter.disabled=true;try{await api("sj-queue-decision",{id:$("#editQueueId").value,decision:"edit",changes});$("#editQueueDialog").close();await loadQueue();toast("Исправления сохранены")}catch(err){toast(err.message)}finally{e.submitter.disabled=false}};
$$(".content-request").forEach(b=>b.onclick=()=>requestMaterial(b.dataset.mode));$("#contentForm").onsubmit=async e=>{if(e.submitter?.value!=="submit")return;e.preventDefault();const mode=$("#contentMode").value,subject=$("#contentSubject").value.trim(),task=$("#contentPrompt").value.trim(),sources=$("#contentSources").value.trim();const text=mode==="note"?`Добавь в очередь теоретический конспект. Предмет: ${subject}. Тема и требования: ${task}. Источники: ${sources||"нет"}. action строго note.`:`Добавь в очередь решение практического ДЗ. Предмет: ${subject}. Условие: ${task}. Источники: ${sources||"нет"}. action строго homework_solver.`;try{const data=await api("sj-chat",{text,history:[]});$("#contentDialog").close();$("#contentForm").reset();toast(data.queued?.length?"Запрос добавлен в очередь":"Предложение не создано");await loadQueue();switchView("queue")}catch(err){toast(err.message)}};
const bootstrapped=applyBootstrap();const initial=location.hash.slice(1);if(titles[initial])switchView(initial);loadQueue();loadRepositoryData();if(bootstrapped)toast("n8n и Cloudflare настроены автоматически");
