const views=[['home','⌂','Главная'],['approvals','◎','Подтверждения'],['tasks','◇','Задачи'],['schedule','□','Расписание'],['news','✦','Новости'],['homework','✓','Домашние задания'],['books','▤','Учебники'],['files','⌘','Файлы проекта']];
const state={view:'home',schedule:[],news:[],homework:[],books:[],tasks:[],proposals:[],meta:{},busy:false};
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const empty=text=>`<div class="empty">${esc(text)}</div>`;
const pending=()=>state.proposals.filter(x=>x.status==='pending');
const apiBase=()=>String(localStorage.getItem('spirit_api_base')||'').replace(/\/$/,'');
const apiKey=()=>String(localStorage.getItem('spirit_api_key')||'');
function acceptLauncherUrl(){const params=new URLSearchParams(location.search);const supplied=params.get('api');if(!supplied)return;try{const url=new URL(supplied);if(url.protocol==='https:'&&url.hostname.endsWith('.trycloudflare.com'))localStorage.setItem('spirit_api_base',url.origin)}catch{}params.delete('api');const query=params.toString();history.replaceState(null,'',`${location.pathname}${query?`?${query}`:''}${location.hash}`)}
async function coreRequest(path,options={}){const base=apiBase();if(!base)throw new Error('not_configured');const response=await fetch(`${base}/webhook/${path}`,{...options,headers:{'Content-Type':'application/json','X-Spirit-Key':apiKey(),...(options.headers||{})}});const data=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
const schedulePanel=()=>`<section class="panel"><div class="panel-head"><div><span class="kicker">МЭШ + Calendar</span><h3>Расписание</h3></div><span class="pill">${esc(state.meta.scheduleStatus||'ожидание')}</span></div><div class="list">${state.schedule.length?state.schedule.map((x,i)=>`<article class="row"><time>${esc(x.start)}<small>${esc(x.end)}</small></time><span class="accent" style="opacity:${Math.max(.45,1-i*.1)}"></span><div><strong>${esc(x.subject)}</strong><small>${x.room?'Кабинет '+esc(x.room):esc(x.note||'')}</small></div><span class="badge">${esc(x.label||`${i+1} урок`)}</span></article>`).join(''):empty('n8n ещё не загрузил расписание')}</div></section>`;
const sourceLine=item=>item.source_title?`<small>Источник: ${item.source_url?`<a href="${esc(item.source_url)}" target="_blank" rel="noreferrer">${esc(item.source_title)} ↗</a>`:esc(item.source_title)}</small>`:'';
const approvalsPanel=(limit=99)=>`<section class="panel approvals-panel"><div class="panel-head"><div><span class="kicker">Ничего без тебя</span><h3>Очередь подтверждений</h3></div><span class="pill pending-pill">${pending().length}</span></div>${pending().length?pending().slice(0,limit).map(item=>`<article class="approval-card"><div class="approval-top"><span class="proposal-type">${esc(item.proposal_type)}</span><span class="confidence">${Math.round(Number(item.confidence||0)*100)}%</span></div><strong>${esc(item.title)}</strong><p>${esc(item.reason)}</p>${sourceLine(item)}<div class="approval-actions"><button data-decision="reject" data-id="${esc(item.id)}" class="secondary">Отклонить</button><button data-decision="approve" data-id="${esc(item.id)}" class="primary">Подтвердить</button></div></article>`).join(''):empty('Новых изменений нет')}</section>`;
const quadrantNames={1:['Важно и срочно','Сделать сейчас'],2:['Важно, не срочно','Запланировать'],3:['Срочно, не важно','Сделать быстро'],4:['Не срочно и не важно','Можно отказаться']};
const taskBoard=()=>`<div class="quadrant-grid">${[1,2,3,4].map(q=>{const tasks=state.tasks.filter(x=>Number(x.quadrant)===q&&x.status==='open');return `<section class="quadrant q${q}"><div class="quadrant-head"><div><span>0${q}</span><strong>${quadrantNames[q][0]}</strong><small>${quadrantNames[q][1]}</small></div><b>${tasks.length}</b></div>${tasks.length?tasks.map(task=>`<article class="task-card"><strong>${esc(task.title)}</strong><p>${esc(task.description||task.subject||'')}</p>${task.due_at?`<time>${esc(task.due_at)}</time>`:''}${sourceLine(task)}</article>`).join(''):empty('Пока пусто')}</section>`}).join('')}</div>`;
function render(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));const title=views.find(x=>x[0]===state.view)?.[2]||'Главная';document.querySelector('#page-title').textContent=title;const app=document.querySelector('#app');if(state.view==='home')app.innerHTML=`<section class="command-card"><div><span class="kicker">Быстрый ввод</span><h2>Что изменилось или что нужно сделать?</h2></div><form id="quick-intake"><input name="text" required placeholder="Например: нужно исправить двойку по алгебре до завтра"><button class="primary" ${state.busy?'disabled':''}>${state.busy?'Разбираю…':'Предложить'}</button></form></section><div class="summary-strip"><button data-view="approvals"><strong>${pending().length}</strong><span>ждут подтверждения</span></button><button data-view="tasks"><strong>${state.tasks.filter(x=>x.status==='open').length}</strong><span>открытых задач</span></button><div><strong>${esc(state.meta.updatedAt||'—')}</strong><span>обновление данных</span></div></div><div class="dashboard-grid">${approvalsPanel(2)}${schedulePanel()}</div>`;if(state.view==='approvals')app.innerHTML=approvalsPanel();if(state.view==='tasks')app.innerHTML=taskBoard();if(state.view==='schedule')app.innerHTML=`<div class="page-grid">${schedulePanel()}<section class="panel"><span class="kicker">Правило безопасности</span><h3>Сначала предложение</h3><p class="callout">Изменения расписания и Calendar применяются только после подтверждения в очереди.</p></section></div>`;if(state.view==='news')app.innerHTML=`<section class="panel">${empty('Свежих выжимок пока нет')}</section>`;if(state.view==='homework')app.innerHTML=`<div class="cards">${state.homework.length?state.homework.map(x=>`<article class="card"><div class="card-icon">✓</div><strong>${esc(x.subject)}</strong><p>${esc(x.task)}</p></article>`).join(''):empty('Домашние задания ещё не загружены')}</div>`;if(state.view==='books')app.innerHTML=`<div class="cards">${state.books.length?state.books.map(x=>`<article class="card"><div class="card-icon">▤</div><strong>${esc(x.title)}</strong><p>${esc(x.description||'')}</p></article>`).join(''):empty('Каталог учебников пуст')}</div><div class="callout">Сами PDF остаются локально.</div>`;if(state.view==='files')app.innerHTML=`<section class="panel">${[['ai-worker','Локальное ядро'],['github-pages','Интерфейс'],['mesh-parser','МЭШ'],['workflows','n8n'],['docs','Документация']].map(x=>`<div class="file-row"><span>▸</span><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</section>`}
async function loadStatic(){for(const name of ['schedule','news','homework','books','meta'])try{const r=await fetch(`./data/${name}.json`,{cache:'no-store'});if(r.ok)state[name]=await r.json()}catch{}try{const r=await fetch('./data/state.json',{cache:'no-store'});if(r.ok){const data=await r.json();state.tasks=data.tasks||[];state.proposals=data.proposals||[]}}catch{}render()}
async function refreshLive(){if(!apiBase()){document.querySelector('#sync-status').textContent='Нужно подключить';return}try{const data=await coreRequest('spirit-state');state.tasks=data.tasks||[];state.proposals=data.proposals||[];document.querySelector('#sync-status').textContent='n8n подключён';render()}catch{document.querySelector('#sync-status').textContent='Нет связи с n8n'}}
async function submitIntake(text){if(!apiBase()){document.querySelector('#connection-dialog').showModal();return}state.busy=true;render();try{const data=await coreRequest('spirit-intake',{method:'POST',body:JSON.stringify({text,source:{type:'web',title:'Веб-интерфейс'}})});state.proposals=[...(data.proposals||[]),...state.proposals];state.view='approvals'}catch(error){alert(`Не удалось передать в n8n: ${error.message}`)}finally{state.busy=false;render()}}
async function decide(id,decision){if(!apiBase()){document.querySelector('#connection-dialog').showModal();return}try{await coreRequest('spirit-decision',{method:'POST',body:JSON.stringify({proposal_id:id,decision})});await refreshLive()}catch(error){alert(`Не удалось выполнить действие: ${error.message}`)}}
acceptLauncherUrl();document.querySelector('#today').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());document.querySelector('#navigation').innerHTML=views.map(([id,icon,label])=>`<button class="nav-item ${id==='home'?'active':''}" data-view="${id}"><span>${icon}</span>${label}</button>`).join('');document.addEventListener('click',event=>{const view=event.target.closest('[data-view]');if(view){state.view=view.dataset.view;render();return}const action=event.target.closest('[data-decision]');if(action)decide(action.dataset.id,action.dataset.decision)});document.addEventListener('submit',event=>{if(event.target.id==='quick-intake'){event.preventDefault();const value=new FormData(event.target).get('text');if(String(value||'').trim())submitIntake(String(value).trim())}});document.querySelector('#connection-settings').addEventListener('click',()=>{document.querySelector('#api-base').value=apiBase();document.querySelector('#api-key').value=apiKey();document.querySelector('#connection-dialog').showModal()});document.querySelector('#save-connection').addEventListener('click',event=>{event.preventDefault();localStorage.setItem('spirit_api_base',document.querySelector('#api-base').value.trim().replace(/\/$/,''));localStorage.setItem('spirit_api_key',document.querySelector('#api-key').value);document.querySelector('#connection-dialog').close();refreshLive()});loadStatic().then(refreshLive);
