const views=[['home','⌂','Главная'],['schedule','□','Расписание'],['news','✦','Новости'],['homework','✓','Домашние задания'],['books','▤','Учебники'],['files','⌘','Файлы проекта']];
const state={view:'home',schedule:[],news:[],homework:[],books:[],meta:{}};
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const empty=text=>`<div class="empty">${esc(text)}</div>`;
const schedulePanel=()=>`<section class="panel"><div class="panel-head"><div><span class="kicker">МЭШ + Calendar</span><h3>Расписание</h3></div><span class="pill">${esc(state.meta.scheduleStatus||'ожидание')}</span></div><div class="list">${state.schedule.length?state.schedule.map((x,i)=>`<article class="row"><time>${esc(x.start)}<small>${esc(x.end)}</small></time><span class="accent" style="opacity:${Math.max(.45,1-i*.1)}"></span><div><strong>${esc(x.subject)}</strong><small>${x.room?'Кабинет '+esc(x.room):esc(x.note||'')}</small></div><span class="badge">${esc(x.label||`${i+1} урок`)}</span></article>`).join(''):empty('n8n ещё не загрузил расписание')}</div></section>`;
const newsPanel=()=>`<section class="panel"><div class="panel-head"><div><span class="kicker">Почта</span><h3>Важное</h3></div><span class="pill">${state.news.length}</span></div>${state.news.length?state.news.map(x=>`<article class="notice"><span class="notice-icon">!</span><div><strong>${esc(x.title)}</strong><p>${esc(x.summary)}</p></div></article>`).join(''):empty('Свежих выжимок пока нет')}</section>`;
function render(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));const title=views.find(x=>x[0]===state.view)?.[2]||'Главная';document.querySelector('#page-title').textContent=title;const app=document.querySelector('#app');
 if(state.view==='home'){const next=state.schedule[0];app.innerHTML=`<section class="hero-card"><div><span class="hero-label">Следующий урок</span><h2>${esc(next?.subject||'Данные готовятся')}</h2><p>${next?`${esc(next.start)}–${esc(next.end)}${next.room?' · кабинет '+esc(next.room):''}`:'n8n обновит эту страницу автоматически'}</p></div><div class="hero-side"><strong>${esc(state.meta.updatedAt||'—')}</strong><span>последнее обновление</span></div></section><div class="dashboard-grid">${schedulePanel()}${newsPanel()}</div>`}
 if(state.view==='schedule')app.innerHTML=`<div class="page-grid">${schedulePanel()}<section class="panel"><span class="kicker">Как это работает</span><h3>n8n → GitHub</h3><p class="callout">Workflow обновляет файл <b>schedule.json</b>, а эта страница автоматически показывает свежие данные. Секреты в сайт не попадают.</p></section></div>`;
 if(state.view==='news')app.innerHTML=`<div class="page-grid">${newsPanel()}<section class="panel"><span class="kicker">Источники</span><h3>Две почты</h3><div class="file-row"><span>●</span><strong>Личный Gmail</strong><small>через n8n</small></div><div class="file-row"><span>●</span><strong>Почта лицея</strong><small>через пересылку</small></div></section></div>`;
 if(state.view==='homework')app.innerHTML=`<div class="cards">${state.homework.length?state.homework.map(x=>`<article class="card"><div class="card-icon">✓</div><strong>${esc(x.subject)}</strong><p>${esc(x.task)}</p><p><b>${esc(x.due||'Без срока')}</b></p></article>`).join(''):empty('Домашние задания ещё не загружены')}</div>`;
 if(state.view==='books')app.innerHTML=`<div class="cards">${state.books.length?state.books.map(x=>`<article class="card"><div class="card-icon">▤</div><strong>${esc(x.title)}</strong><p>${esc(x.description||'')}</p>${x.url?`<p><a href="${esc(x.url)}" target="_blank" rel="noreferrer">Открыть источник ↗</a></p>`:''}</article>`).join(''):empty('Каталог учебников пуст')}</div><div class="callout">В публичный репозиторий добавляем только каталог и разрешённые ссылки — не личные файлы и не защищённые авторским правом PDF.</div>`;
 if(state.view==='files')app.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="kicker">GitHub</span><h3>Jeronion / SpiritJeronion</h3></div><span class="pill">main</span></div>${[['github-pages','Интерфейс GitHub Pages'],['mesh-parser','Интеграция с МЭШ'],['workflows','Безопасные экспорты n8n'],['docs','Архитектура и инструкции'],['README.md','Описание проекта']].map(x=>`<div class="file-row"><span>▸</span><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</section>`;
}
async function load(){const names=['schedule','news','homework','books','meta'];await Promise.all(names.map(async name=>{try{const r=await fetch(`./data/${name}.json`,{cache:'no-store'});if(r.ok)state[name]=await r.json()}catch{}}));document.querySelector('#sync-status').textContent='Данные загружены';render()}
document.querySelector('#today').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());document.querySelector('#navigation').innerHTML=views.map(([id,icon,label])=>`<button class="nav-item ${id==='home'?'active':''}" data-view="${id}"><span>${icon}</span>${label}</button>`).join('');document.addEventListener('click',e=>{const button=e.target.closest('[data-view]');if(button){state.view=button.dataset.view;render()}});load();
